pipeline {
    agent none

    stages {
        stage('Backend') {
            agent{
                docker {
                    image 'maven:3-sapmachine-22'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
