pipeline {
    agent none

    stages {
        stage('Test') {
            agent{
                docker {
                    image 'maven:3-sapmachine-22'
                }
            }
            steps {
                sh 'mvn --version'
			}
        }
        
        stage('Build'){
            agent { 
				dockerfile {
                   filename 'Dockerfile'  
				   dir '/docs/CI-CD/Jenkins/wordpress-project'
				}
            }
            steps {
                sh 'docker stack deploy -c stack.yml wordpress'
            }
        }
    }
}